name: Deploy website on push
on: 
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # server: 194.233.94.185
        # username: ${{ secrets.ftp_username_maruf }}
        # password: ${{ secrets.ftp_password_maruf }}
        # protocol: ftps
        # port: 21
        # server-dir: /maruf.bizzself.top/
        # timeout: 120000
