name: Deploy website on push
on: 
  push:
    branches:
      - nusrat
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 194.233.94.185
        username: ${{ secrets.ftp_username_nusrat }}
        password: ${{ secrets.ftp_password_nusrat }}
        protocol: ftps
        # port: 21
        # server-dir: /maruf.bizzself.top/
        # timeout: 120000
